apiVersion: v1
kind: Service
metadata:
  name: sftp-emory-service
spec:
  type: LoadBalancer
  loadBalancerIP: 104.154.169.144
  loadBalancerSourceRanges:
    - 34.197.57.115/32
    - 34.197.58.165/32
    - 35.161.51.209/32
#    - 160.202.36.37/32     #add local ip to access pod locally
  ports:
  - port: 9022
    targetPort: 9022
    protocol: TCP
  selector:
    app: sftp-emory