apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: sftp-umass-deployment
 spec:
   selector:
     matchLabels:
       app: sftp-umass
   replicas: 1
   template:
     metadata:
       labels:
         app: sftp-umass
     spec:
       containers:
       - name: sftp-umass
         image: gcr.io/emeritus-data-science/sftp-umass:latest
         resources:
           requests:
             memory: "4Gi"
             cpu: "500m"
         env:
           - name: bucket
             value: "sis_umass"
           - name: port_var
             value: "9022"
           - name: username
             valueFrom:
               secretKeyRef:
                 name: sftp-umass-credentials
                 key: user
           - name: password
             valueFrom:
               secretKeyRef:
                 name: sftp-umass-credentials
                 key: password

         ports:
         - containerPort: 9022

 ---
 apiVersion: v1
 kind: Service
 metadata:
   name: sftp-umass-service
 spec:
   type: LoadBalancer
   loadBalancerIP: 34.68.54.82
   ports:
   - port: 9022
     targetPort: 9022
     protocol: TCP
   selector:
     app: sftp-umass 