apiVersion: apps/v1
kind: Deployment
metadata:
  name: sftp-emory-deployment
spec:
  selector:
    matchLabels:
      app: sftp-emory
  replicas: 1
  template:
    metadata:
      labels:
        app: sftp-emory
    spec:
      containers:
      - name: sftp-emory
        image: gcr.io/emeritus-data-science/sftp-emory:latest
        resources:
          requests:
            memory: "8Gi"
            cpu: "500m"
          limits:
            memory: "12Gi"
            cpu: "700m"
        env:
          - name: bucket
            value: "sis_emory"
          - name: port_var
            value: "9022"
          - name: username
            valueFrom:
              secretKeyRef:
                name: sftp-emory-credentials
                key: user
          - name: password
            valueFrom:
              secretKeyRef:
                name: sftp-emory-credentials
                key: password

        ports:
        - containerPort: 9022